import { neon } from "@neondatabase/serverless";

async function seed() {
  const databaseUrl = process.env.POSTGRES_URL;
  if (!databaseUrl) {
    throw new Error("POSTGRES_URL environment variable is not set");
  }
  const sql = neon(databaseUrl);

  await sql`
    CREATE TABLE IF NOT EXISTS routers (
      id SERIAL PRIMARY KEY,
      slug VARCHAR(255) UNIQUE NOT NULL,
      name VARCHAR(255) NOT NULL,
      brand VARCHAR(100) NOT NULL,
      image_url TEXT NOT NULL,
      price DECIMAL(10, 2) NOT NULL,
      wifi_standard VARCHAR(50) NOT NULL,
      speed VARCHAR(100) NOT NULL,
      frequency_bands VARCHAR(100) NOT NULL,
      ports TEXT NOT NULL,
      description TEXT NOT NULL,
      features TEXT[] NOT NULL,
      rating DECIMAL(2, 1) NOT NULL
    )
  `;

  const routers = [
    {
      slug: "asus-rog-rapture-gt-be98-pro",
      name: "ASUS ROG Rapture GT-BE98 Pro",
      brand: "ASUS",
      image_url: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop",
      price: 699.99,
      wifi_standard: "WiFi 7 (802.11be)",
      speed: "24,000 Mbps",
      frequency_bands: "Quad-band (2.4 GHz + 5 GHz + 5 GHz + 6 GHz)",
      ports: "1x 10G WAN, 1x 10G LAN, 3x 2.5G LAN, 4x 1G LAN, 2x USB 3.0",
      description: "The ASUS ROG Rapture GT-BE98 Pro is a flagship WiFi 7 gaming router built for esports-level performance, featuring RangeBoost Plus technology and multi-link operation (MLO). It offers dedicated gaming acceleration, advanced QoS, and a built-in gaming VPN for lag-free online play.",
      features: [
        "WiFi 7 with Multi-Link Operation (MLO)",
        "320 MHz channel bandwidth support",
        "Quad-band concurrent wireless",
        "10G WAN + 10G LAN ports",
        "ASUS AiMesh whole-home mesh support",
        "Built-in gaming VPN with 50+ country servers",
        "Advanced traffic analyzer and QoS",
        "OLED system status display",
      ],
      rating: 4.7,
    },
    {
      slug: "tp-link-archer-be800",
      name: "TP-Link Archer BE800",
      brand: "TP-Link",
      image_url: "https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=600&h=400&fit=crop",
      price: 449.99,
      wifi_standard: "WiFi 7 (802.11be)",
      speed: "19,000 Mbps",
      frequency_bands: "Tri-band (2.4 GHz + 5 GHz + 6 GHz)",
      ports: "1x 10G SFP+ WAN, 1x 10G LAN, 2x 2.5G LAN, 4x 1G LAN, 2x USB 3.0",
      description: "The TP-Link Archer BE800 is one of the most capable WiFi 7 tri-band routers in its price class, delivering up to 19 Gbps aggregate throughput with BE19000 classification. It supports the latest 4K-QAM modulation and Multi-Link Operation for dramatically reduced latency.",
      features: [
        "WiFi 7 BE19000 tri-band",
        "4K-QAM for 20% higher throughput",
        "Multi-Link Operation (MLO)",
        "10G SFP+ fiber WAN port",
        "HomeCare Pro security suite",
        "TP-Link OneMesh compatible",
        "Advanced parental controls",
        "Simultaneous 4T4R on all bands",
      ],
      rating: 4.5,
    },
    {
      slug: "netgear-nighthawk-rs700s",
      name: "Netgear Nighthawk RS700S",
      brand: "Netgear",
      image_url: "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&h=400&fit=crop",
      price: 599.99,
      wifi_standard: "WiFi 7 (802.11be)",
      speed: "19,000 Mbps",
      frequency_bands: "Tri-band (2.4 GHz + 5 GHz + 6 GHz)",
      ports: "1x 10G WAN, 1x 10G LAN, 4x 1G LAN, 2x USB 3.0",
      description: "The Netgear Nighthawk RS700S is Netgear's premier WiFi 7 router, offering a clean and powerful platform for demanding home networks. It features the Qualcomm Networking Pro 820 chipset for consistent multi-gig performance across all three bands.",
      features: [
        "WiFi 7 BE19000 tri-band",
        "Qualcomm Networking Pro 820 chipset",
        "Netgear Armor cybersecurity (Bitdefender)",
        "10G WAN + 10G LAN ports",
        "Automatic Quality of Service (QoS)",
        "Smart Connect band steering",
        "OFDMA and MU-MIMO",
        "Circle smart parental controls",
      ],
      rating: 4.4,
    },
    {
      slug: "asus-zenwifi-pro-et12",
      name: "ASUS ZenWiFi Pro ET12",
      brand: "ASUS",
      image_url: "https://images.unsplash.com/photo-1562408590-e32931084e23?w=600&h=400&fit=crop",
      price: 449.99,
      wifi_standard: "WiFi 6E (802.11ax)",
      speed: "11,000 Mbps",
      frequency_bands: "Tri-band (2.4 GHz + 5 GHz + 6 GHz)",
      ports: "1x 2.5G WAN, 1x 2.5G LAN, 3x 1G LAN, 1x USB 3.0",
      description: "The ASUS ZenWiFi Pro ET12 is a tri-band WiFi 6E mesh system designed for large homes, sold as a 2-pack covering up to 5,500 sq ft. Its dedicated 6 GHz backhaul ensures the fastest possible speeds reach every node without congesting client bands.",
      features: [
        "WiFi 6E tri-band mesh system (2-pack)",
        "Dedicated 6 GHz wireless backhaul",
        "Covers up to 5,500 sq ft",
        "ASUS AiProtection Pro security",
        "Instant Guard VPN",
        "OFDMA + MU-MIMO support",
        "AiMesh compatible for expansion",
        "Advanced parental controls with content filtering",
      ],
      rating: 4.6,
    },
    {
      slug: "eero-pro-7",
      name: "Amazon eero Pro 7",
      brand: "Amazon eero",
      image_url: "https://images.unsplash.com/photo-1558089687-f282d8132652?w=600&h=400&fit=crop",
      price: 299.99,
      wifi_standard: "WiFi 7 (802.11be)",
      speed: "9,400 Mbps",
      frequency_bands: "Tri-band (2.4 GHz + 5 GHz + 6 GHz)",
      ports: "1x 2.5G WAN, 1x 2.5G LAN",
      description: "The eero Pro 7 is Amazon's flagship WiFi 7 mesh router, combining incredibly simple setup with powerful tri-band performance. It integrates seamlessly with the broader Amazon ecosystem, including Alexa voice controls and Ring security devices.",
      features: [
        "WiFi 7 tri-band mesh node",
        "TrueMesh technology for self-healing network",
        "2.5G WAN and LAN ports",
        "Alexa built-in for voice network management",
        "eero Plus subscription for advanced security",
        "Thread border router for smart home devices",
        "Automatic firmware updates",
        "Works with existing eero mesh systems",
      ],
      rating: 4.5,
    },
    {
      slug: "tp-link-deco-be65",
      name: "TP-Link Deco BE65",
      brand: "TP-Link",
      image_url: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&h=400&fit=crop",
      price: 219.99,
      wifi_standard: "WiFi 7 (802.11be)",
      speed: "6,500 Mbps",
      frequency_bands: "Tri-band (2.4 GHz + 5 GHz + 6 GHz)",
      ports: "1x 2.5G WAN, 1x 2.5G LAN, 1x 1G LAN",
      description: "The TP-Link Deco BE65 offers WiFi 7 mesh performance at a mid-range price point, making next-generation wireless accessible for most households. It supports MLO (Multi-Link Operation) to bond multiple bands for lower latency and greater reliability.",
      features: [
        "WiFi 7 BE6500 tri-band mesh",
        "Multi-Link Operation (MLO)",
        "2.5G WAN + 2.5G LAN ports",
        "TP-Link HomeCare security",
        "Easy Deco app management",
        "Works as router or access point",
        "OFDMA for dense device environments",
        "Covers up to 2,300 sq ft per unit",
      ],
      rating: 4.3,
    },
    {
      slug: "netgear-orbi-970",
      name: "Netgear Orbi 970",
      brand: "Netgear",
      image_url: "https://images.unsplash.com/photo-1610552050890-244d8ff5b5ff?w=600&h=400&fit=crop",
      price: 1499.99,
      wifi_standard: "WiFi 7 (802.11be)",
      speed: "27,000 Mbps",
      frequency_bands: "Quad-band (2.4 GHz + 5 GHz + 6 GHz + 6 GHz)",
      ports: "1x 10G WAN, 3x 2.5G LAN, 1x USB 3.0",
      description: "The Netgear Orbi 970 is an ultra-premium quad-band WiFi 7 mesh system for massive homes, with a single unit covering up to 6,000 sq ft. It uses dual 6 GHz radios — one for backhaul and one for clients — ensuring maximum throughput at every node.",
      features: [
        "WiFi 7 quad-band BE27000",
        "Dual 6 GHz radios for dedicated backhaul",
        "10G WAN port",
        "Covers up to 6,000 sq ft per unit",
        "Netgear Armor security suite included",
        "Automatic band steering and optimization",
        "Circle smart parental controls",
        "Supports up to 200+ connected devices",
      ],
      rating: 4.6,
    },
    {
      slug: "ubiquiti-unifi-dream-router",
      name: "Ubiquiti UniFi Dream Router",
      brand: "Ubiquiti",
      image_url: "https://images.unsplash.com/photo-1551703599-6b3e8379aa8c?w=600&h=400&fit=crop",
      price: 199.00,
      wifi_standard: "WiFi 6 (802.11ax)",
      speed: "3,500 Mbps",
      frequency_bands: "Dual-band (2.4 GHz + 5 GHz)",
      ports: "1x GbE WAN, 4x GbE LAN, 1x USB 3.0",
      description: "The Ubiquiti UniFi Dream Router is an all-in-one UniFi OS console, router, and WiFi 6 access point that delivers prosumer-grade networking at an accessible price. It runs the full UniFi Network application locally, offering enterprise-grade visibility and control without a subscription fee.",
      features: [
        "Built-in UniFi Network application",
        "Supports UniFi Protect, Access, and Talk",
        "Local hosting — no cloud subscription required",
        "Advanced VLAN and firewall rules",
        "IDS/IPS intrusion detection",
        "Can manage additional UniFi APs and switches",
        "1.3\" color LCD for system status",
        "PoE output on LAN port 1 (802.3af)",
      ],
      rating: 4.4,
    },
    {
      slug: "linksys-velop-pro-7",
      name: "Linksys Velop Pro 7",
      brand: "Linksys",
      image_url: "https://images.unsplash.com/photo-1519558260268-cde7e03a0152?w=600&h=400&fit=crop",
      price: 349.99,
      wifi_standard: "WiFi 7 (802.11be)",
      speed: "9,300 Mbps",
      frequency_bands: "Tri-band (2.4 GHz + 5 GHz + 6 GHz)",
      ports: "1x 2.5G WAN, 1x 2.5G LAN",
      description: "The Linksys Velop Pro 7 brings WiFi 7 mesh performance to Linksys's well-regarded Velop platform, offering fast whole-home coverage with a clean tower design. It supports the latest MLO and 4K-QAM innovations for improved speeds and reliability.",
      features: [
        "WiFi 7 tri-band mesh node",
        "Multi-Link Operation for reduced latency",
        "2.5G WAN + 2.5G LAN ports",
        "Velop Intelligence adaptive routing",
        "Intelligent mesh self-optimization",
        "Works with Linksys app and web dashboard",
        "Easy daisy-chain wired backhaul support",
        "Covers up to 3,000 sq ft per node",
      ],
      rating: 4.2,
    },
    {
      slug: "tp-link-archer-ax55",
      name: "TP-Link Archer AX55",
      brand: "TP-Link",
      image_url: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=400&fit=crop",
      price: 99.99,
      wifi_standard: "WiFi 6 (802.11ax)",
      speed: "3,000 Mbps",
      frequency_bands: "Dual-band (2.4 GHz + 5 GHz)",
      ports: "1x GbE WAN, 4x GbE LAN, 1x USB 3.0",
      description: "The TP-Link Archer AX55 is a best-selling dual-band WiFi 6 router that delivers reliable AX3000 performance for everyday households at a very affordable price. It supports OFDMA, MU-MIMO, and 1024-QAM for efficient handling of dozens of simultaneous connected devices.",
      features: [
        "WiFi 6 AX3000 dual-band",
        "OFDMA and MU-MIMO for multi-device efficiency",
        "1024-QAM for 25% higher speed vs WiFi 5",
        "USB 3.0 for NAS or printer sharing",
        "TP-Link HomeCare security suite",
        "WPA3 encryption support",
        "Tether app for easy mobile management",
        "Beamforming for targeted signal strength",
      ],
      rating: 4.3,
    },
  ];

  for (const router of routers) {
    await sql`
      INSERT INTO routers (slug, name, brand, image_url, price, wifi_standard, speed, frequency_bands, ports, description, features, rating)
      VALUES (
        ${router.slug},
        ${router.name},
        ${router.brand},
        ${router.image_url},
        ${router.price},
        ${router.wifi_standard},
        ${router.speed},
        ${router.frequency_bands},
        ${router.ports},
        ${router.description},
        ${router.features},
        ${router.rating}
      )
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        brand = EXCLUDED.brand,
        image_url = EXCLUDED.image_url,
        price = EXCLUDED.price,
        wifi_standard = EXCLUDED.wifi_standard,
        speed = EXCLUDED.speed,
        frequency_bands = EXCLUDED.frequency_bands,
        ports = EXCLUDED.ports,
        description = EXCLUDED.description,
        features = EXCLUDED.features,
        rating = EXCLUDED.rating
    `;
  }

  console.log("Seeded 10 routers successfully!");
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seeding failed:", err);
    process.exit(1);
  });
